


-- Contraintes d'intégrité
ALTER TABLE BOOKING.BOOKING_CONTENEUR ADD FOREIGN KEY (IDDEMANDE_BOOKING) REFERENCES BOOKING.P_DEMANDE_BOOKING (IDDEMANDE_BOOKING);
ALTER TABLE BOOKING.SORTIE_ATTRIBUTION_TC ADD FOREIGN KEY (IDATTRIBUTION_TC) REFERENCES BOOKING.ATTRIBUTION_TC (IDATTRIBUTION_TC);
ALTER TABLE BOOKING.PARAM_TC_REEFER ADD FOREIGN KEY (IDBOOKING_CONTENEUR) REFERENCES BOOKING.BOOKING_CONTENEUR (IDBOOKING_CONTENEUR);
ALTER TABLE BOOKING.BOOKING_FINAL_TC ADD FOREIGN KEY (IDDEMANDE_BOOKING) REFERENCES BOOKING.P_DEMANDE_BOOKING (IDDEMANDE_BOOKING);
ALTER TABLE BOOKING.MOTIF_REFUS_BOOKING ADD FOREIGN KEY (IDDEMANDE_BOOKING) REFERENCES BOOKING.P_DEMANDE_BOOKING (IDDEMANDE_BOOKING);
ALTER TABLE BOOKING.ATTRIBUTION_TC ADD FOREIGN KEY (IDBOOKING_CONTENEUR) REFERENCES BOOKING.BOOKING_CONTENEUR (IDBOOKING_CONTENEUR);
ALTER TABLE BOOKING.A_ETAPE_BOOKING ADD FOREIGN KEY (CODEETAPE_SUIVI_BOOKING) REFERENCES BOOKING.ETAPE_SUIVI_BOOKING (CODEETAPE_SUIVI_BOOKING);
ALTER TABLE BOOKING.A_ETAPE_BOOKING ADD FOREIGN KEY (IDDEMANDE_BOOKING) REFERENCES BOOKING.P_DEMANDE_BOOKING (IDDEMANDE_BOOKING);
ALTER TABLE BOOKING.P_DEMANDE_BOOKING ADD FOREIGN KEY (IDUTILISATEUR_CLIENT) REFERENCES BOOKING.USERS (ID);
-- ALTER TABLE BOOKING.UTILISATEUR_CLIENT_F_COMPTET ADD FOREIGN KEY (IDUTILISATEUR_CLIENT) REFERENCES BOOKING.USERS (ID);
ALTER TABLE BOOKING.OT_POSITIONNEMENT_TC ADD FOREIGN KEY (IDPOSITIONNEMENT) REFERENCES BOOKING.POSITIONNEMENT_TC (IDPOSITIONNEMENT);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDTRANSPORTEUR) REFERENCES BOOKING.TRANSPORTEUR (IDTRANSPORTEUR);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDCHAUFFEUR) REFERENCES BOOKING.CHAUFFEUR (IDCHAUFFEUR);
ALTER TABLE BOOKING.CHAUFFEUR ADD FOREIGN KEY (IDTRANSPORTEUR) REFERENCES BOOKING.TRANSPORTEUR (IDTRANSPORTEUR);
ALTER TABLE BOOKING.BON_PHYSIQUE ADD FOREIGN KEY (IDPOSITIONNEMENT) REFERENCES BOOKING.POSITIONNEMENT_TC (IDPOSITIONNEMENT);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDACTIVITES) REFERENCES BOOKING.ACTIVITES (IDACTIVITES);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDATTRIBUTION_TC) REFERENCES BOOKING.ATTRIBUTION_TC (IDATTRIBUTION_TC);
ALTER TABLE BOOKING.EMPOTAGE_TC_POSIT ADD FOREIGN KEY (IDPOSITIONNEMENT) REFERENCES BOOKING.POSITIONNEMENT_TC (IDPOSITIONNEMENT);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDCHAUFFEUR) REFERENCES BOOKING.CHAUFFEUR (IDCHAUFFEUR);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDTRANSPORTEUR) REFERENCES BOOKING.TRANSPORTEUR (IDTRANSPORTEUR);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDPOSITIONNEMENT) REFERENCES BOOKING.POSITIONNEMENT_TC (IDPOSITIONNEMENT);
ALTER TABLE BOOKING.SORTIE_RETOUR_CONTENEUR ADD FOREIGN KEY (IDRETOUR_CONTENEUR) REFERENCES BOOKING.RETOUR_CONTENEUR (IDRETOUR_CONTENEUR);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDLIEU_APPRO) REFERENCES BOOKING.LIEU_APPRO (IDLIEU_APPRO);
ALTER TABLE BOOKING.ATTRIBUTION_TC ADD FOREIGN KEY (IDLIEU_APPRO) REFERENCES BOOKING.LIEU_APPRO (IDLIEU_APPRO);
ALTER TABLE BOOKING.FIN_RETOUR_TC ADD FOREIGN KEY (IDRETOUR_CONTENEUR) REFERENCES BOOKING.RETOUR_CONTENEUR (IDRETOUR_CONTENEUR);
ALTER TABLE BOOKING.FIN_POSIT_TC ADD FOREIGN KEY (IDPOSITIONNEMENT) REFERENCES BOOKING.POSITIONNEMENT_TC (IDPOSITIONNEMENT);
ALTER TABLE BOOKING.FIN_RETOUR_TC ADD FOREIGN KEY (IDLIEU_APPRO_CLI_ARR) REFERENCES BOOKING.LIEU_APPRO (IDLIEU_APPRO);
ALTER TABLE BOOKING.FIN_RETOUR_TC ADD FOREIGN KEY (IDLIEU_APPRO_CAM) REFERENCES BOOKING.LIEU_APPRO (IDLIEU_APPRO);
ALTER TABLE BOOKING.EMPOTAGE_TC_POSIT ADD FOREIGN KEY (CODESTATION_EMPOTAGE) REFERENCES BOOKING.STATION_EMPOTAGE (CODESTATION_EMPOTAGE);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDLIEU_APPRO_CAM) REFERENCES BOOKING.LIEU_APPRO (IDLIEU_APPRO);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDLIEU_APPRO_CLIP) REFERENCES BOOKING.LIEU_APPRO (IDLIEU_APPRO);
ALTER TABLE BOOKING.EMB_CONTENEUR ADD FOREIGN KEY (IDRETOUR_CONTENEUR) REFERENCES BOOKING.RETOUR_CONTENEUR (IDRETOUR_CONTENEUR);



grant references on EOLIS.USERNAME to BOOKING;
grant references on EOLIS.PRODUIT to BOOKING;
grant references on EOLIS.TCS_BASE to BOOKING;
grant references on EOLIS.ESCALE to BOOKING;
grant references on EOLIS.PORT to BOOKING;
grant references on PARC.ENGIN to BOOKING;
grant references on PARC.SORTIE to BOOKING;
grant references on PARC.ORDTRAV to BOOKING;
grant references on PARC.TYPENGIN to BOOKING;
grant select on PARC.TYPENGIN to BOOKING;
grant select on BOOKING.PANNES_TYPENGIN to PARC;


drop index PARC.CLEENGIN;
drop index PARC.WDIDX130968149023;
alter table PARC.ENGIN add constraint CLEENGIN primary key (IdEngin);


ALTER TABLE BOOKING.PANNES_TYPENGIN ADD FOREIGN KEY (IDPANNE) REFERENCES BOOKING.PANNES (IDPANNE);
ALTER TABLE BOOKING.PANNES_TYPENGIN ADD FOREIGN KEY (CODETYPE) REFERENCES PARC.TYPENGIN (CODETYPE);



ALTER TABLE BOOKING.ATTRIBUTION_TC ADD FOREIGN KEY (CODEUSER_SAISI) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.ATTRIBUTION_TC ADD FOREIGN KEY (CODEUSER_MODIF) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.P_DEMANDE_BOOKING ADD FOREIGN KEY (PRODUIT) REFERENCES EOLIS.PRODUIT (PRODUIT);
-- ALTER TABLE BOOKING.P_DEMANDE_BOOKING ADD FOREIGN KEY (CODEETAPE_SUIVI_BOOKING) REFERENCES BOOKING.ETAPE_SUIVI_BOOKING (CODEETAPE_SUIVI_BOOKING);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (USER_SAISI) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (USER_MODIF) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.FIN_POSIT_TC ADD FOREIGN KEY (CODEUSER_MODIF) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.FIN_RETOUR_TC ADD FOREIGN KEY (CODEUSER_MODIF) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (USER_SAISI) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (USER_MODIF) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.FIN_RETOUR_TC ADD FOREIGN KEY (agent_trans) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.FIN_POSIT_TC ADD FOREIGN KEY (AGENT_COM) REFERENCES EOLIS.USERNAME (CODEUSER);
ALTER TABLE BOOKING.ATTRIBUTION_TC ADD FOREIGN KEY (NO_TC) REFERENCES EOLIS.TCS_BASE (NO_TC);
ALTER TABLE BOOKING.EMB_CONTENEUR ADD FOREIGN KEY (NOESCALE) REFERENCES EOLIS.ESCALE (NOESCALE);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDLIEU_DEPART) REFERENCES EOLIS.PORT (CODEPORT);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDLIEU_ARRIVE) REFERENCES EOLIS.PORT (CODEPORT);
ALTER TABLE BOOKING.STATION_EMPOTAGE ADD FOREIGN KEY (IDLIEU) REFERENCES EOLIS.PORT (CODEPORT);
ALTER TABLE BOOKING.LIEU_APPRO ADD FOREIGN KEY (IDLIEU) REFERENCES EOLIS.PORT (CODEPORT);


ALTER TABLE BOOKING.SORTIE_ATTRIBUTION_TC ADD FOREIGN KEY (IDSORTIE) REFERENCES PARC.SORTIE (IDBON);
ALTER TABLE BOOKING.SORTIE_RETOUR_CONTENEUR ADD FOREIGN KEY (IDSORTIE) REFERENCES PARC.SORTIE (IDBON);
ALTER TABLE BOOKING.ATTRIBUTION_TC ADD FOREIGN KEY (idclipon) REFERENCES PARC.ENGIN (IdEngin);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDREMORQUE) REFERENCES PARC.ENGIN (IdEngin);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDREMORQUE) REFERENCES PARC.ENGIN (IdEngin);
ALTER TABLE BOOKING.POSITIONNEMENT_TC ADD FOREIGN KEY (IDCAMION) REFERENCES PARC.ENGIN (IdEngin);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDCAMION) REFERENCES PARC.ENGIN (IdEngin);
ALTER TABLE BOOKING.RETOUR_CONTENEUR ADD FOREIGN KEY (IDCLIPON) REFERENCES PARC.ENGIN (IdEngin);
-- ALTER TABLE BOOKING.R_LIEU ADD FOREIGN KEY (CODE_ZONE) REFERENCES PARC.ZONELIVR (CODE_ZONE);
ALTER TABLE BOOKING.OT_POSITIONNEMENT_TC ADD FOREIGN KEY (IDOT) REFERENCES PARC.ORDTRAV (IDOT);
ALTER TABLE BOOKING.BON_PHYSIQUE ADD FOREIGN KEY (IDSORTIE) REFERENCES PARC.SORTIE (IDBON);




ALTER TABLE BOOKING.SORTIE_FIN_RETOUR_TC ADD FOREIGN KEY (IDFIN_RETOUR_TC) REFERENCES BOOKING.FIN_RETOUR_TC (IDFIN_RETOUR_TC);
ALTER TABLE BOOKING.SORTIE_FIN_RETOUR_TC ADD FOREIGN KEY (IDSORTIE) REFERENCES PARC.SORTIE (IDBON);








--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table role_has_permissions
--
-- ALTER TABLE BOOKING.role_has_permissions ADD FOREIGN KEY (permission_id) REFERENCES BOOKING.permissions (id);
-- ALTER TABLE BOOKING.role_has_permissions ADD FOREIGN KEY (role_id) REFERENCES BOOKING.roles (id);

--
-- Contraintes pour la table user_has_permissions
--
-- ALTER TABLE BOOKING.user_has_permissions ADD FOREIGN KEY (permission_id) REFERENCES BOOKING.permissions (id);
-- ALTER TABLE BOOKING.user_has_permissions ADD FOREIGN KEY (user_id) REFERENCES BOOKING.users (id);

--
-- Contraintes pour la table user_has_roles
--
-- ALTER TABLE BOOKING.user_has_roles ADD FOREIGN KEY (role_id) REFERENCES BOOKING.roles (id);
-- ALTER TABLE BOOKING.user_has_roles ADD FOREIGN KEY (user_id) REFERENCES BOOKING.users (id);






alter table BOOKING.BON_PHYSIQUE add constraint
BOOKING.BON_PHYSIQUE_CON unique (IDPOSITIONNEMENT,IDSORTIE)
;   

alter table BOOKING.BOOKING_CONTENEUR add constraint
BOOKING.BOOKING_CONTENEUR_CON_DBKG unique (IDDEMANDE_BOOKING)
;   

alter table BOOKING.BOOKING_FINAL_TC add constraint
BOOKING.BOOKING_FINAL_TC_CON_DBKG unique (IDDEMANDE_BOOKING)
;   

alter table BOOKING.BOOKING_FINAL_TC add constraint
BOOKING.BOOKING_FINAL_TC_CON_DECL unique (NO_DECLARATION)
;   

alter table BOOKING.EMB_CONTENEUR add constraint
BOOKING.EMB_CONTENEUR_CON unique (IDRETOUR_CONTENEUR)
;   

alter table BOOKING.EMPOTAGE_TC_POSIT add constraint
BOOKING.EMPOTAGE_TC_POSIT_CON unique (IDPOSITIONNEMENT)
;   

alter table BOOKING.FIN_POSIT_TC add constraint
BOOKING.FIN_POSIT_TC_CON unique (IDPOSITIONNEMENT)
;   

alter table BOOKING.FIN_RETOUR_TC add constraint
BOOKING.FIN_RETOUR_TC_CON unique (IDRETOUR_CONTENEUR)
;   

alter table BOOKING.MOTIF_REFUS_BOOKING add constraint
BOOKING.MOTIF_REFUS_BOOKING_CON unique (IDDEMANDE_BOOKING)
;   

alter table BOOKING.OT_POSITIONNEMENT_TC add constraint
BOOKING.OT_POSITIONNEMENT_TC_CON unique (IDPOSITIONNEMENT,IDOT)
;   

alter table BOOKING.PARAM_TC_REEFER add constraint
BOOKING.PARAM_TC_REEFER_CON unique (IDBOOKING_CONTENEUR)
;   

alter table BOOKING.POSITIONNEMENT_TC add constraint
BOOKING.POSITIONNEMENT_TC_CON unique (IDATTRIBUTION_TC)
;   

alter table BOOKING.P_DEMANDE_BOOKING add constraint
BOOKING.P_DEMANDE_BOOKING_CON unique (NO_BOOKING)
;   

alter table BOOKING.RETOUR_CONTENEUR add constraint
BOOKING.RETOUR_CONTENEUR_CON unique (IDPOSITIONNEMENT)
;   

alter table BOOKING.SORTIE_ATTRIBUTION_TC add constraint
BOOKING.SORTIE_ATTRIBUTION_REEF_CON unique (IDATTRIBUTION_TC,IDSORTIE)
;   

alter table BOOKING.SORTIE_RETOUR_CONTENEUR add constraint
BOOKING.SORTIE_RETOUR_CONTENEUR_CON unique (IDRETOUR_CONTENEUR,IDSORTIE)
;   

alter table BOOKING.SORTIE_FIN_RETOUR_TC add constraint
BOOKING.SORTIE_FIN_RETOUR_TC_CON unique (IDFIN_RETOUR_TC,IDSORTIE)
;

alter table BOOKING.PERMISSIONS add constraint
BOOKING.PERMISSIONS_CON unique (NAME,GUARD_NAME)
;   

alter table BOOKING.ROLES add constraint
BOOKING.ROLES_CON unique (NAME,GUARD_NAME)
;   

alter table "BOOKING"."PANNES_TYPENGIN" add constraint  "PANNES_TYPENGIN_PK" primary key ("IDPANNE","CODETYPE")
/

alter table "BOOKING"."ATTRIBUTION_CLIPON" add constraint  "BOOKING"."ATTRIBUTION_CLIPON_PK" primary key ("IDATTRIBUTION_TC","IDCLIPON")
/

ALTER TABLE "BOOKING"."ATTRIBUTION_CLIPON" ADD CONSTRAINT "BOOKING"."ATTRIBUTION_CLIPON_FK" 
FOREIGN KEY ("BOOKING"."IDATTRIBUTION_TC")
REFERENCES "BOOKING"."ATTRIBUTION_TC" ("IDATTRIBUTION_TC")

/
ALTER TABLE "BOOKING"."ATTRIBUTION_CLIPON" ADD CONSTRAINT "BOOKING"."ATTRIBUTION_CLIPON_FK2" 
FOREIGN KEY ("BOOKING"."IDLIEU_APPRO")
REFERENCES "BOOKING"."LIEU_APPRO" ("IDLIEU_APPRO")

/

ALTER TABLE "BOOKING"."ATTRIBUTION_CLIPON_RETOUR" ADD CONSTRAINT "BOOKING"."ATTRIBUTION_CLIPON_RETOUR_FK" 
FOREIGN KEY ("BOOKING"."IDRETOUR_CONTENEUR")
REFERENCES "BOOKING"."RETOUR_CONTENEUR" ("IDRETOUR_CONTENEUR")

/
