CREATE INDEX BOOKING.WDIDX_A_ATTRIBUTION_REEFE00069 ON BOOKING.ATTRIBUTION_TC (IDBOOKING_CONTENEUR);
CREATE INDEX BOOKING.WDIDX_A_ATTRIBUTION_REEFE00070 ON BOOKING.ATTRIBUTION_TC (NO_TC);
CREATE INDEX BOOKING.WDIDX_A_ATTRIBUTION_REEFE00071 ON BOOKING.ATTRIBUTION_TC (idclipon);
CREATE INDEX BOOKING.WDIDX_A_ATTRIBUTION_REEFE00072 ON BOOKING.ATTRIBUTION_TC (CODEUSER_SAISI);
CREATE INDEX BOOKING.WDIDX_A_ATTRIBUTION_REEFE00073 ON BOOKING.ATTRIBUTION_TC (CODEUSER_MODIF);
CREATE INDEX BOOKING.WDIDX_A_ATTRIBUTION_REEFE00074 ON BOOKING.ATTRIBUTION_TC (IDLIEU_APPRO);


CREATE INDEX BOOKING.WDIDX_A_ETAPE_BOOKING_COD00075 ON BOOKING.A_ETAPE_BOOKING (CODEETAPE_SUIVI_BOOKING);
CREATE INDEX BOOKING.WDIDX_A_ETAPE_BOOKING_IDD00076 ON BOOKING.A_ETAPE_BOOKING (IDDEMANDE_BOOKING);
CREATE INDEX BOOKING.WDIDX_A_ETAPE_BOOKING_ID_AGENT ON BOOKING.A_ETAPE_BOOKING (ID_AGENT);


CREATE INDEX BOOKING.WDIDX_BON_PHYSIQUE_IDPOSI00077 ON BOOKING.BON_PHYSIQUE (IDPOSITIONNEMENT);
CREATE INDEX BOOKING.WDIDX_BON_PHYSIQUE_IDSORTIE ON BOOKING.BON_PHYSIQUE (IDSORTIE);
CREATE INDEX BOOKING.WDIDX_BON_PHYSIQUE_IDSORT00078 ON BOOKING.BON_PHYSIQUE (IDSORTIE,IDPOSITIONNEMENT);


CREATE INDEX BOOKING.WDIDX_BOOKING_CONTENEURS_00079 ON BOOKING.BOOKING_CONTENEUR (IDDEMANDE_BOOKING);
CREATE INDEX BOOKING.WDIDX_BOOKING_CONTENEURS_00080 ON BOOKING.BOOKING_CONTENEUR (CODETYPE_TC);


CREATE INDEX BOOKING.WDIDX_BOOKING_FINAL_TC_ID00081 ON BOOKING.BOOKING_FINAL_TC (IDDEMANDE_BOOKING);


CREATE INDEX BOOKING.WDIDX_CHAUFFEUR_IDTRANSPORTEUR ON BOOKING.CHAUFFEUR (IDTRANSPORTEUR);


CREATE INDEX BOOKING.WDIDX_EMB_CONTENEUR_IDRET00082 ON BOOKING.EMB_CONTENEUR (IDRETOUR_CONTENEUR);
CREATE INDEX BOOKING.WDIDX_EMB_CONTENEUR_NOESCALE ON BOOKING.EMB_CONTENEUR (NOESCALE);


CREATE INDEX BOOKING.WDIDX_EMPOTAGE_TC_POSIT_I00083 ON BOOKING.EMPOTAGE_TC_POSIT (IDPOSITIONNEMENT);
CREATE INDEX BOOKING.WDIDX_EMPOTAGE_TC_POSIT_C00084 ON BOOKING.EMPOTAGE_TC_POSIT (CODESTATION_EMPOTAGE);


CREATE INDEX BOOKING.WDIDX_FIN_POSIT_TC_IDPOSI00085 ON BOOKING.FIN_POSIT_TC (IDPOSITIONNEMENT);
CREATE INDEX BOOKING.WDIDX_FIN_POSIT_TC_AGENT_COM ON BOOKING.FIN_POSIT_TC (AGENT_COM);
CREATE INDEX BOOKING.WDIDX_FIN_POSIT_TC_CODEUS00086 ON BOOKING.FIN_POSIT_TC (CODEUSER_MODIF);


CREATE INDEX BOOKING.WDIDX_FIN_RETOUR_TC_IDRET00087 ON BOOKING.FIN_RETOUR_TC (IDRETOUR_CONTENEUR);
CREATE INDEX BOOKING.WDIDX_FIN_RETOUR_TC_IDLIE00088 ON BOOKING.FIN_RETOUR_TC (IDLIEU_APPRO_CLI_ARR);
CREATE INDEX BOOKING.WDIDX_FIN_RETOUR_TC_IDLIE00089 ON BOOKING.FIN_RETOUR_TC (IDLIEU_APPRO_CAM);
CREATE INDEX BOOKING.WDIDX_FIN_RETOUR_TC_agent00090 ON BOOKING.FIN_RETOUR_TC (agent_trans);
CREATE INDEX BOOKING.WDIDX_FIN_RETOUR_TC_CODEU00091 ON BOOKING.FIN_RETOUR_TC (CODEUSER_MODIF);


CREATE INDEX BOOKING.WDIDX_LIEU_APPRO_IDLIEU ON BOOKING.LIEU_APPRO (IDLIEU);


CREATE INDEX BOOKING.WDIDX_MOTIF_REFUS_BOOKING00092 ON BOOKING.MOTIF_REFUS_BOOKING (IDDEMANDE_BOOKING);


CREATE INDEX BOOKING.WDIDX_OT_POSIT_TC_IDPOSIT00093 ON BOOKING.OT_POSITIONNEMENT_TC (IDPOSITIONNEMENT);
CREATE INDEX BOOKING.WDIDX_OT_POSIT_TC_IDOT ON BOOKING.OT_POSITIONNEMENT_TC (IDOT);
CREATE INDEX BOOKING.WDIDX_OT_POSIT_TC_IDOT_ID00094 ON BOOKING.OT_POSITIONNEMENT_TC (IDOT,IDPOSITIONNEMENT);


CREATE INDEX BOOKING.WDIDX_P_DEMANDE_BOOKING_I00095 ON BOOKING.P_DEMANDE_BOOKING (IDUTILISATEUR_CLIENT);
CREATE INDEX BOOKING.WDIDX_P_DEMANDE_BOOKING_CT_NUM ON BOOKING.P_DEMANDE_BOOKING (CT_NUM);
CREATE INDEX BOOKING.WDIDX_P_DEMANDE_BOOKING_P00096 ON BOOKING.P_DEMANDE_BOOKING (PAYEURFRET);
CREATE INDEX BOOKING.WDIDX_P_DEMANDE_BOOKING_C00097 ON BOOKING.P_DEMANDE_BOOKING (PRODUIT);
-- CREATE INDEX BOOKING.WDIDX_P_DEMANDE_BOOKING_P00098 ON BOOKING.P_DEMANDE_BOOKING (CODEETAPE_SUIVI_BOOKING);


CREATE INDEX BOOKING.WDIDX_PARAM_TC_REEFER_IDB00098 ON BOOKING.PARAM_TC_REEFER (IDBOOKING_CONTENEUR);


CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00099 ON BOOKING.POSITIONNEMENT_TC (IDTRANSPORTEUR);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00100 ON BOOKING.POSITIONNEMENT_TC (IDCHAUFFEUR);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00101 ON BOOKING.POSITIONNEMENT_TC (IDCAMION);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00102 ON BOOKING.POSITIONNEMENT_TC (IDREMORQUE);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_U00103 ON BOOKING.POSITIONNEMENT_TC (USER_SAISI);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_U00104 ON BOOKING.POSITIONNEMENT_TC (USER_MODIF);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00105 ON BOOKING.POSITIONNEMENT_TC (IDACTIVITES);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00106 ON BOOKING.POSITIONNEMENT_TC (IDLIEU_DEPART);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00107 ON BOOKING.POSITIONNEMENT_TC (IDLIEU_ARRIVE);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00108 ON BOOKING.POSITIONNEMENT_TC (IDATTRIBUTION_TC);
CREATE INDEX BOOKING.WDIDX_POSITIONNEMENT_TC_I00109 ON BOOKING.POSITIONNEMENT_TC (IDLIEU_APPRO);


CREATE INDEX BOOKING.WDIDX_R_LIEU_lib_lieu ON BOOKING.R_LIEU (lib_lieu);
CREATE INDEX BOOKING.WDIDX_R_LIEU_CODE_ZONE ON BOOKING.R_LIEU (CODE_ZONE);


CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00110 ON BOOKING.RETOUR_CONTENEUR (IDREMORQUE);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00111 ON BOOKING.RETOUR_CONTENEUR (IDCAMION);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00112 ON BOOKING.RETOUR_CONTENEUR (IDCHAUFFEUR);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00113 ON BOOKING.RETOUR_CONTENEUR (IDTRANSPORTEUR);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00114 ON BOOKING.RETOUR_CONTENEUR (IDPOSITIONNEMENT);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_US00115 ON BOOKING.RETOUR_CONTENEUR (USER_SAISI);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_US00116 ON BOOKING.RETOUR_CONTENEUR (USER_MODIF);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00117 ON BOOKING.RETOUR_CONTENEUR (IDCLIPON);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00118 ON BOOKING.RETOUR_CONTENEUR (IDLIEU_APPRO_CAM);
CREATE INDEX BOOKING.WDIDX_RETOUR_CONTENEUR_ID00119 ON BOOKING.RETOUR_CONTENEUR (IDLIEU_APPRO_CLIP);


CREATE INDEX BOOKING.WDIDX_SORTIE_A_ATTRIBUTIO00120 ON BOOKING.SORTIE_ATTRIBUTION_TC (IDATTRIBUTION_TC);
CREATE INDEX BOOKING.WDIDX_SORTIE_A_ATTRIBUTIO00121 ON BOOKING.SORTIE_ATTRIBUTION_TC (IDSORTIE);
CREATE INDEX BOOKING.WDIDX_SORTIE_A_ATTRIBUTIO00122 ON BOOKING.SORTIE_ATTRIBUTION_TC (IDSORTIE,IDATTRIBUTION_TC);


CREATE INDEX BOOKING.WDIDX_SORTIE_RETOUR_CONTE00123 ON BOOKING.SORTIE_RETOUR_CONTENEUR (IDRETOUR_CONTENEUR);
CREATE INDEX BOOKING.WDIDX_SORTIE_RETOUR_CONTE00124 ON BOOKING.SORTIE_RETOUR_CONTENEUR (IDSORTIE);
CREATE INDEX BOOKING.WDIDX_SORTIE_RETOUR_CONTE00125 ON BOOKING.SORTIE_RETOUR_CONTENEUR (IDSORTIE,IDRETOUR_CONTENEUR);


CREATE INDEX BOOKING.WDIDX_SORTIE_FIN_RETOUR1 ON BOOKING.SORTIE_FIN_RETOUR_TC (IDFIN_RETOUR_TC);
CREATE INDEX BOOKING.WDIDX_SORTIE_FIN_RETOUR2 ON BOOKING.SORTIE_FIN_RETOUR_TC (IDSORTIE);
CREATE INDEX BOOKING.WDIDX_SORTIE_FIN_RETOUR3 ON BOOKING.SORTIE_FIN_RETOUR_TC (IDSORTIE,IDFIN_RETOUR_TC);


CREATE INDEX BOOKING.WDIDX_STATION_EMPOTAGE_IDLIEU ON BOOKING.STATION_EMPOTAGE (IDLIEU);


CREATE INDEX BOOKING.WDIDX_UTILISATEUR_CLIENT_00126 ON BOOKING.PAYEUR_FRET_TIER (CT_NUM);
CREATE INDEX BOOKING.WDIDX_UTILISATEUR_CLIENT_00127 ON BOOKING.PAYEUR_FRET_TIER (PAYEUR_FRET);
CREATE INDEX BOOKING.WDIDX_UTILISATEUR_CLIENT_00128 ON BOOKING.PAYEUR_FRET_TIER (CT_NUM,PAYEUR_FRET);








--
-- Index pour la table password_resets
--
-- create index BOOKING.PASSWORD_RESETS_EMAIL_INDEX on BOOKING.PASSWORD_RESETS (EMAIL);

--
-- Index pour la table role_has_permissions
--
-- create index BOOKING.ROLE_HAS_PERMS_ROLE_ID_FOREIGN on BOOKING.ROLE_HAS_PERMISSIONS (ROLE_ID);

-- create UNIQUE index BOOKING.ROLE_HAS_PERMISSIONS_IDX1 on BOOKING.ROLE_HAS_PERMISSIONS (PERMISSION_ID,ROLE_ID);

--
-- Index pour la table users
--

-- create UNIQUE index BOOKING.users_email_unique on booking.users (email);

--
-- Index pour la table user_has_permissions
--
-- create index BOOKING.user_has__perms_id_foreign on BOOKING.user_has_permissions (permission_id);

-- create UNIQUE index BOOKING.user_has_permissions_IDX1 on BOOKING.user_has_permissions (user_id,permission_id);

--
-- Index pour la table user_has_roles
--
-- create index BOOKING.user_has_roles_user_id_foreign on BOOKING.user_has_roles (USER_ID);

-- create UNIQUE index BOOKING.user_has_roles_IDX1 on BOOKING.user_has_roles (role_id,user_id);






